---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  attributes:
    consul:
      config:
        datacenter: dc1
        encrypt: Dt3P9SpKGAR/DIUN1cDirg==

platforms:
  - name: ubuntu-16.04
  - name: ubuntu-14.04
  - name: centos-6.5
  - name: centos-7
  - name: windows2012r2
    driver_config:
      #box_url: https://wrock.blob.core.windows.net/vhds/vbox2012r2.box
      communicator: winrm
      vm_hostname: false    
    transport:
      name: winrm

suites:
  - name: default
    require_chef_omnibus: true
    run_list:
      - recipe[consul-ng::default]
    attributes:
      consul:
        config:
          bootstrap: true
          server: true
